timeout = 30_000
enableInlineShortcodes = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy.vimeo]
disabled = true
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true
disableInlineCSS = true

[privacy.instagram]
disabled = true
simple = true

[privacy.youtube]
disabled = true
privacyEnhanced = true