baseURL = 'https://cleminso.xyz/'
languageCode = 'en-us'
title = 'TL;DR'
theme = 'PaperMod'
Copyright="© 2023 cleminso.eth |"

[params.HomeInfoParams]
title = "Boouh!"
content = """
Welcome to my blog!
I love learning, but I find that I struggle to express what I’m learning and restitch the knowledge to restructure my thoughts.
That’s why this site exists.

You will discover two formats:

-> TL;DR is a weekly, short series about 2-3 subjects to take the most important things about them. Sometime, I will present a discovery project

-> Product review focuses on one subject or product. I will write to analyze and highlight the core motivations for the subject.

Because we're often hyped about a subject, but we rarely can argue and support why, I thing or love this thing.

So, this blog is where I will mostly share about UX products based on my studies and current learning. It's also a training place and my portfolio in one way.
Enjoy!
"""

[[params.SocialIcons]]
name = "twitter"
url = "https://twitter.com/cleminso"

[[params.SocialIcons]]
name = "github"
url = "https://github.com/cleminso"

[[menu.main]]
identifier= "TL;DR"
name= "TL;DR"
url= "/tldr/"
weight= 10
[[menu.main]]
identifier= "Product Review"
name= "Product Review"
url= "/product-review/"
weight= 5
[[menu.main]]
identifier= "Tags"
name= "Tags"
url= "/tags/"
weight= 20
[[menu.main]]
identifier= "Now"
name= "Now"
url= "/now/"

enableRobotsTXT= true
buildDrafts= false
buildFuture= false
buildExpired= false

#googleAnalytics: UA-123-45

[minify]
disableXML= true
minifyOutput= true

[params]
# env = "production"
# title = "ExampleSite"
# description = "."
keywords = [ "UX Review", "Blockchain", "Web3 Product" ]
author = "Cleminso"
# images = [ "<link or path of image for opengraph, twitter-cards>" ]
# DateFormat = "January 2, 2006"
# defaultTheme = "auto"
# disableThemeToggle = false
Copyright="cleminso.eth"
ShowReadingTime = true
# ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
# UseHugoToc = true
# disableSpecial1stPost = false
disableScrollToTop = false
# comments = false
# hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

# [outputs]
# home = [ "HTML", "RSS", "JSON" ]

# [assets]
# favicon = "<link / abs url>"
# favicon16x16 = "<link / abs url>"
# favicon32x32 = "<link / abs url>"
# apple_touch_icon = "<link / abs url>"
# safari_pinned_tab = "<link / abs url>"

# [label]
# text = "Home"
# icon = "/apple-touch-icon.png"
# iconHeight = 35

[profileMode]
enabled = true
title = "Cleminso Portfolio"
subtitle = "This is subtitle"
imageUrl = "<img location>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

  [[profileMode.buttons]]
  name = "Posts"
  url = "posts"

  [[profileMode.buttons]]
  name = "Tags"
  url = "tags"

[homeInfoParams]
Title = "Hello world"
Content = "Welcome to my blog"

#   socialIcons:
[[socialIcons]]
name="twitter"
url= "https://twitter.com/cleminso"
  #   - name: stackoverflow
  #     url: "https://stackoverflow.com"
  #   - name: github
  #     url: "https://github.com/"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

#   cover:
#     hidden: true # hide everywhere but not in structured data
#     hiddenInList: true # hide on list pages and home
#     hiddenInSingle: true # hide on single page

#   editPost:
#     URL: "https://github.com/<path_to_repo>/content"
#     Text: "Suggest Changes" # edit text
#     appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]


# # Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#   highlight:
#     noClasses: false
#     # anchorLineNos: true
#     # codeFences: true
#     # guessSyntax: true
#     # lineNos: true
#     # style: monokai
